"""Initial Migration

Revision ID: 9f70965eec79
Revises: 800456c24ab2
Create Date: 2020-07-17 00:56:13.760008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f70965eec79'
down_revision = '800456c24ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pitches_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('pitch', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('user_id', sa.String(), nullable=False))
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'pitch')
    op.drop_column('pitches', 'date_created')
    op.drop_column('pitches', 'category')
    op.drop_table('comments')
    # ### end Alembic commands ###
